services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: progWeb/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: progWeb/backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
