services:
  backend:
    container_name: awesome_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vikasraj/awesome_server
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
