version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: progweb/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/appFrontend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: progweb/backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/usr/src/appBackend
